# Generated by Django 3.2.8 on 2021-11-07 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listings', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.TextField(max_length=12)),
                ('message', models.TextField(blank=True)),
                ('contact', models.DateField(blank=True, default=datetime.datetime.now)),
                ('useri_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
