# Generated by Django 3.2.8 on 2021-11-07 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='useri_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='contact',
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
