# Generated by Django 4.1.1 on 2022-11-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211107_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
