# Generated by Django 4.1.1 on 2022-11-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contacts_appointment_date_contacts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='pending', max_length=15),
        ),
    ]
