# Generated by Django 4.1.1 on 2022-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contacts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
