# Generated by Django 4.1.1 on 2022-10-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specs',
            field=models.CharField(default='Cardio', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
