# Generated by Django 4.1.1 on 2022-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '__first__'),
        ('realtors', '0002_doctor_specs_alter_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ManyToManyField(to='listings.listing'),
        ),
    ]
